# -- Enter the values for each of the respective variables listed

# -- IP Addresses for the different nodes wishing to be created
CONTROLLER_IP="10.0.0.11"
NETWORK_IP="10.0.0.21"
NETWORK_TUNNEL_IP="10.0.1.21"
COMPUTE1_IP="10.0.0.31"
COMPUTE1_TUNNEL_IP="10.0.1.31"

# -- Database information
MYSQL_ROOT_PASSWORD="root"

# -- Keystone information
KEYSTONE_DB_PASSWORD="keystone"
KEYSTONE_AUTH_TOKEN="f4d705f6c44d63f076a1"  # generated by "openssl rand -hex 10"
KEYSTONE_ADMIN_PASSWORD="keystone"
KEYSTONE_ADMIN_EMAIL="root@root.com"
KEYSTONE_DEMO_PASSWORD="keystone_demo"
KEYSTONE_DEMO_EMAIL="demo@demo.com"
